# Generated by Django 3.0.8 on 2020-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_auto_20200728_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='превью изображения'),
        ),
    ]
