# Generated by Django 3.0.8 on 2020-07-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='originals', verbose_name='файл изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails', verbose_name='превью изображения'),
        ),
    ]
