# Generated by Django 3.0.8 on 2020-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0004_auto_20200728_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(default=100, verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(default=100, verbose_name='ширина'),
        ),
    ]
